.github/workflows/release.yml

When an RC is published on top of an existing RC, the `rc` identifier doubles. Example from [`@supabase/auth-js`](https://www.npmjs.com/package/@supabase/auth-js/v/2.64.3-rc.rc.rc.3) which uses pretty much the same Github Actions workflow file.
The fix is to change the `git describe --tags --exclude` to a value that actually excludes [tags that start with `rc`](https://github.com/supabase/ssr/releases/tag/rc0.4.0-rc.2).

ci: fix doubling of `rc` version identifier

---

src/utils/__snapshots__/helpers.spec.ts.snap
src/utils/helpers.spec.ts
src/utils/helpers.ts

`parse`, `serialize` from `cookie` were exported as-is. That's not super useful for importing outside of the library, so they're deprecated and in their stead adding `parseCookieHeader`, `serializeCookieHeader` which works with the `getAll`, `setAll` cookie methods more ergonomically. 
For example, instead of:
```typescript
getAll() {
const parsed = parse(request.headers.get('Cookie') ?? '')
return Object.keys(parsed).map((name) => ({ name, value: parsed[name] }))
}
```
You can just use:
```typescript
getAll() {
return parseCookieHeader(req.headers.get('Cookie') ?? '')
}
```

fix: deprecate `parse`, `serialize` exports for more useful functions

---

src/createBrowserClient.ts

Fixes the deprecation TSDoc on `createBrowserClient` to not show up if you don't pass in any options.
Discussion: https://github.com/orgs/supabase/discussions/27037#discussioncomment-9764831

fix: fix `createBrowserClient` deprecation tsdoc

---

src/cookies.ts

Allows calling `createBrowserClient` without throwing an error when not in a browser context (i.e. `window` is missing).
This is especially useful when using in Next.js Pre-Rendering mode where the client's non-`auth` namespaces could be useful, such as to load public data from PostgREST.
If however the `auth` namespace is used, the `setAll` handler function will throw an error indicating to the user that they're doing something wrong. This shouldn't come up in Pre-Rendering mode ever.
See: https://github.com/orgs/supabase/discussions/27037#discussioncomment-9852948

fix: allow use of `createBrowserClient` without `window` present

---

CHANGELOG.md
src/createServerClient.ts

Currently, create server client doesn't seem to set cookies when MFA Challenge is verified

fix: set cookies when mfa challenge is verified

---

src/createServerClient.ts

Bug fix
When resetting a user's password with an email template which has a URL defining the `type` value as `recovery`, and using the `verifyOtp` method to process the token_hash and type, the SSR server client's `onAuthStateChange` function does not recognize the `PASSWORD_RECOVERY` event that verifyOtp fires. This prevents the code [here](https://github.com/supabase/ssr/blob/main/src/createServerClient.ts#L199-L205) from running; resulting in the new session not being saved to cookies, and the user is not considered logged in.
Fixes #21
User is logged in.
Replaces PR #24

fix: set cookies for password recovery event

---

.prettierignore

Since `CHANGELOG.md` is maintained by Release Please, ignoring prettier on it.

ci: remove CHANGELOG.md from prettier check

---

.github/workflows/release.yml

If a specific patch is made on a release branch, it will always use the `patched` NPM dist tag. This also checks if the patched release branch is the latest release branch to use the `latest` NPM dist tag.

ci: fix `latest` npm dist tag when patching versions

---

package-lock.json
package.json

This is causing an issue for a user when deploying to vercel as it's trying to install this optional dependency. However it doesn't look like this optional dependency is being used anywhere in this project.
Optional dependency is not being used.
Remove optional dependency.
Add any other context or screenshots.

fix: remove optional dependencies

---

src/__snapshots__/createServerClient.spec.ts.snap
src/utils/constants.ts

Some browsers didn't like the large number used by the `Max-Age` default cookie option, causing weird behavior. It's now set to [400 days](https://developer.chrome.com/blog/cookie-max-age-expires).

fix: set `max-age` default cookie option to 400 days

---

src/cookies.ts

#26 but with prettier
Full credit to [pfftdammitchris](https://github.com/pfftdammitchris) for this contribution

fix: check chunkedCookie is string in server client

---

package-lock.json
package.json

Makes the `@types/cookies` dependency a regular one to fix common compilation errors. See #53.

fix: add @types/cookies to dependencies

---

.github/workflows/conventional-commits-lint.js
.github/workflows/conventional-commits.yml

Bug fix, and maintenance to CI
The `github.event` could include shell characters such as ``` in the commit message, which would be interpreted by the shell and can lead to unexpected code execution. Dependabot PRs break because of commit title rules, skip.
Uses intermediate file for getting `github.event` information. Direct shell interpretation doesn't escape special characters, which can cause problems or lead to code execution. Skips the job for dependabot PRs.

chore: workflow cleanup

---

src/createServerClient.ts
src/types.ts

fix type, remove unused imports, fix comments
-
-
Add any other context or screenshots.

fix: update type, remove unused imports, define AuthEvent type

---

package-lock.json
package.json
src/cookies.ts
src/createBrowserClient.ts
src/createServerClient.ts
src/types.ts
src/utils/helpers.ts

- Bump `cookie` package to the latest version.
- Use correct types from `cookie` package.
- Fix typescript warning.
- Cleanup unused imports.
It currently shows up as unfixable security issue in my project.
https://github.com/advisories/GHSA-pxg6-pf52-xh8x
Related issues:
https://github.com/supabase/ssr/issues/73
The new version of this package does not have this security issue.

feat: upgrade cookie dependency and cleanup imports

---

src/createBrowserClient.ts
src/createServerClient.ts

A tiny change that lets Supabase team track usage of `createServerClient` and `createBrowserClient` separately across requests.

fix: add `create*Client` string in `x-client-info`

---

src/__snapshots__/createServerClient.spec.ts.snap
src/cookies.spec.ts
src/cookies.ts
src/createBrowserClient.spec.ts
src/createBrowserClient.ts
src/createServerClient.spec.ts
src/createServerClient.ts
src/utils/chunker.spec.ts
src/utils/chunker.ts

Improves cookie chunk handling by introducing a new cookie encoding scheme that includes the length of the encoded Base64 value. It will prevent reconstructing data from stale cookies.
Due to bad uses of this package, some cookie chunks are not being properly deleted. Meaning that if a session was encoded in 3 chunks now suddenly goes down to 2 chunks, the last chunk is not being deleted. When it gets reconstructed, all the 3 chunks get concatenated and parsed. In some situations this leads to an invalid UTF-8 sequence (mainly because Base64 packs 6 bits into 8).
This PR addresses this by implementing a different Base64 encoding of the chunks. Instead of just splitting up a Base64 string into chunks, the first chunk will now contain the length of the string that follows. This will prevent …

feat: improve cookie chunk handling via base64url+length encoding

---

package-lock.json
package.json

Bumps [`cookie`](https://www.npmjs.com/package/cookie) to 1.0.2 which supports [CHIPS](https://datatracker.ietf.org/doc/html/draft-cutler-httpbis-partitioned-cookies/) cookies.

feat: bump `cookie` to 1.0.2

---

.github/workflows/release.yml
README.md
package-lock.json
package.json
src/index.ts

Feature - Package consolidation and multi-package publishing
Currently, `@supabase/ssr` is only published under its own package name. Meanwhile, the deprecated `@supabase/auth-helpers-*` packages continue to receive thousands of weekly downloads, probably due to LLMs recommending them in code suggestions despite being deprecated for a long time.
The deprecated packages:
- `@supabase/auth-helpers-nextjs` (159k weekly downloads)
- `@supabase/auth-helpers-react`
- `@supabase/auth-helpers-remix`
- `@supabase/auth-helpers-sveltekit`
This PR enables `@supabase/ssr` to be published under multiple package names simultaneously:
1. **Multi-package publishing**: The release workflow now publishes the same codebase under 5 different npm package names:
- `@supabase/ssr` (primary package)
- …

feat: publish SSR under deprecated auth-helpers package names

---

package-lock.json
package.json
src/createBrowserClient.ts
src/createServerClient.ts
src/types.ts
src/utils/helpers.ts

Adds an experimental option `encode` on the `cookies` object when using `createBrowserClient()` and `createServerClient()`.
If this is set to `tokens-only` then only the user's access token and refresh token will be encoded in the cookies, causing significant cookie size savings, often greater than 50%. It utilizes [split session storage in `auth-js`](https://github.com/supabase/supabase-js/pull/1545), with some trade-offs such as the inability to access the `user` property on the `supabase.auth.getSession()` object in the server. This wasn't supposed to be done anyway, and `getClaims()` is a secure alternative for it.

feat: adds `cookies.encode` option allowing minimal cookie sizes
